version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the React app"
      - npm run build
post_build:
  commands:
    - echo "Syncing with S3 using KMS encryption"
    - aws s3 sync dist/ s3://reactpizzaapp --region eu-north-1 --sse aws:kms --delete



artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
